import './globals.css'
import { Inter } from 'next/font/google'
import ContextProviders from './context/ContextProviders'

import { store } from './store/store'
import { Provider } from 'react-redux'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'MyFinance',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Provider store={store}> */}
        <ContextProviders>
          {children}
        </ContextProviders>
        {/* </Provider> */}

      </body>
    </html>
  )
}
